dist: trusty
sudo: false

language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - bsdtar
      - cppcheck
      - libarchive-dev
      - libssl-dev
      - valgrind

script:
  - autoconf --version
  - automake --version
  - ./autogen.sh
  - ./configure
  - make
  - make check
