sudo: false

os: linux
dist: xenial

language: python

python: 3.7

matrix:
  include:
    - env: CC=gcc
    - env: CC=clang

addons:
  apt:
    packages:
      - bsdtar
      - cppcheck
      - libarchive-dev
      - libssl-dev
      - ninja-build
      - valgrind

install:
  - pip --version
  - pip install meson

script:
  - meson --version
  - ninja --version
  - meson build
  - ninja -C build
  - meson test -C build --no-suite lfs
  - cat build/meson-logs/testlog.txt

cache: pip
