language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libarchive-dev libssl-dev

script:
  - autoconf --version
  - automake --version
  - ./autogen.sh
  - ./configure
  - make
