sudo: false

os: linux
dist: trusty

language: python

python: 3.6

matrix:
  include:
    - env: CC=gcc
    - env: CC=clang

addons:
  apt:
    packages:
      - bsdtar
      - cppcheck
      - libarchive-dev
      - libssl-dev
      - valgrind

install:
  - export NINJA_LATEST=$(curl -s https://api.github.com/repos/ninja-build/ninja/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep ninja-linux.zip)
  - wget "$NINJA_LATEST"
  - unzip -q ninja-linux.zip -d build
  - export PATH="$PWD/build:$PATH"
  - pip install meson

script:
  - meson build
  - ninja -C build
  - meson test -C build --no-suite lfs
  - cat build/meson-logs/testlog.txt
